# Generated by Django 5.0.3 on 2024-03-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact_houseinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='image',
            field=models.ImageField(upload_to='image-house'),
        ),
    ]
